services:
  web:
    # Construye la imagen utilizando el Dockerfile
    build: .

    container_name: flask_crud_backend

    # Puerto PC : Puerto contenedor
    ports:
      - "5000:5000"

    # Variables privadas
    env_file:
      - .env

    # Persistencia de la base de datos SQLite
    volumes:
      - sqlite_data:/app/instance

volumes:
  sqlite_data: